# cd /mnt/c/mc/mgmt
# docker-compose up -d

services:

  minecraft:
    container_name: mc
    depends_on:
      - database
    environment:
      ENABLE_RCON: "FALSE"
      EULA: "TRUE"
      MAX_MEMORY: "10G"
      TYPE: "PAPER"
    image: itzg/minecraft-server:latest
    networks:
      - mc
    ports:
      - "25565:25565"
      - "8123:8123"
    restart: "no" 
    volumes:
      - "/mnt/c/mc/data:/data"

  database:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "dynmapdb"
      MYSQL_USER: "dynmapuser"
      MYSQL_PASSWORD: "password"
    networks:
      - mc
    restart: "no"
    volumes:
      - "/home/mysql/mc:/var/lib/mysql"

networks:
  mc:
